// Lexegen autogenerated definition file - do not edit!

enum {
    predef_pat_default = 0,
    pat_comment = 26,
    pat_eof = 29,
    pat_eof_expr = 2,
    pat_id = 24,
    pat_int = 23,
    pat_nl = 28,
    pat_option = 21,
    pat_other_char = 27,
    pat_reg_expr_begin = 3,
    pat_sc_list_begin = 1,
    pat_sep = 22,
    pat_start = 20,
    pat_string_begin = 25,
    pat_string_cont = 16,
    pat_string_end = 4,
    pat_string_eof = 18,
    pat_string_es_a = 7,
    pat_string_es_b = 8,
    pat_string_es_bslash = 14,
    pat_string_es_dquot = 15,
    pat_string_es_f = 9,
    pat_string_es_hex = 6,
    pat_string_es_n = 11,
    pat_string_es_oct = 5,
    pat_string_es_r = 10,
    pat_string_es_t = 12,
    pat_string_es_v = 13,
    pat_string_nl = 17,
    pat_whitespace = 19,
};

enum {
    sc_initial = 0,
    sc_reg_expr = 2,
    sc_sc_list = 3,
    sc_string = 1,
};

struct StateData {
    size_t pat_length = 0;
    char* unread_text = nullptr;
    std::vector<char> text;
    std::vector<int> state_stack;
    void (*get_more)(StateData& data) = nullptr;
};
