// Lexegen autogenerated definition file - do not edit!

enum {
    predef_pat_default = 0,
    pat_sc_list_begin,
    pat_eof_expr,
    pat_reg_expr_begin,
    pat_string_end,
    pat_string_es_oct,
    pat_string_es_hex,
    pat_string_es_a,
    pat_string_es_b,
    pat_string_es_f,
    pat_string_es_r,
    pat_string_es_n,
    pat_string_es_t,
    pat_string_es_v,
    pat_string_es_bslash,
    pat_string_es_dquot,
    pat_string_cont,
    pat_string_nl,
    pat_string_eof,
    pat_whitespace,
    pat_start,
    pat_option,
    pat_sep,
    pat_int,
    pat_id,
    pat_string_begin,
    pat_comment,
    pat_other_char,
    pat_nl,
    pat_eof,
};

enum {
    sc_initial = 0,
    sc_string,
    sc_reg_expr,
    sc_sc_list,
};

struct StateData {
    size_t pat_length = 0;
    char* unread_text = nullptr;
    std::vector<char> text;
    std::vector<int> state_stack;
    void (*get_more)(StateData& data) = nullptr;
};
