// Parsegen autogenerated definition file - do not edit!

enum {
    predef_tt_error = 258,
    tt_eof,
    tt_nl,
    tt_symb,
    tt_sset,
    tt_id,
    tt_string,
    tt_num,
    tt_start,
    tt_option,
    tt_sep,
    tt_sc_list_begin,
    tt_unterm_token,
};

enum {
    act_trail_cont = 1,
    act_or,
    act_cat,
    act_star,
    act_plus,
    act_question,
    act_zero_num,
    act_same_num,
    act_mult_finite,
    act_mult_infinite,
};

enum {
    sc_initial = 0,
};

struct CtxData {
    unsigned reduce_length = 0;
    bool can_recover = false;
    bool rise_error = false;
};
