/* Parsegen autogenerated definition file - do not edit! */
/* clang-format off */

enum {
    predef_tt_error = 258,
    tt_eof,
    tt_nl,
    tt_symb,
    tt_sset,
    tt_id,
    tt_string,
    tt_num,
    tt_start,
    tt_option,
    tt_sep,
    tt_sc_list_begin,
    tt_lexical_error,
    total_token_count
};

enum {
    predef_act_shift = 0,
    predef_act_reduce = 1,
    act_trailing_context,
    act_or,
    act_cat,
    act_star,
    act_plus,
    act_question,
    act_mult_exact,
    act_mult_not_more_than,
    act_mult_not_less_than,
    act_mult_range,
    total_action_count
};

enum {
    sc_initial = 0
};
