/* Parsegen autogenerated definition file - do not edit! */

enum {
    predef_tt_error = 258,
    tt_eof,
    tt_nl,
    tt_symb,
    tt_sset,
    tt_id,
    tt_string,
    tt_num,
    tt_start,
    tt_option,
    tt_sep,
    tt_sc_list_begin,
    tt_unterm_token,
    total_token_count
};

enum {
    predef_act_shift = 0,
    predef_act_reduce = 1,
    act_trail_cont,
    act_or,
    act_cat,
    act_star,
    act_plus,
    act_question,
    act_zero_num,
    act_same_num,
    act_mult_finite,
    act_mult_infinite,
    total_action_count
};

enum {
    sc_initial = 0
};
